esphome:
  name: "flower-monitor"
  friendly_name: "Flower Monitor"

logger:
  level: DEBUG

nrf52:
  board: adafruit_itsybitsy_nrf52840
  dcdc: false
  dfu: true

zigbee:
  sleepy: false
  wipe_on_boot: once

sensor:
  - platform: adc
    pin: P0.02
    name: "Влажность_почвы_1"
    icon: "mdi:water-percent"
    update_interval: 60s
    id: flower_1
  - platform: adc
    pin: P0.03
    name: "Влажность_почвы_2"
    icon: "mdi:water-percent"
    update_interval: 60s
    id: flower_2
  - platform: adc
    pin: P0.04
    name: "Влажность_почвы_3"
    icon: "mdi:water-percent"
    update_interval: 60s
    id: flower_3
  - platform: adc
    pin: P0.05
    name: "Влажность_почвы_4"
    icon: "mdi:water-percent"
    update_interval: 60s
    id: flower_4
